# -*- coding: utf-8 -*-
"""
EDL-resolved mixed-potential model (3-segment electrode) — Debye–Hückel + linear surface charging.

What it does
------------
1) Solves the (linearized) Poisson–Boltzmann equation in a semi-infinite electrolyte above a
   piecewise-constant, 3-segment electrode surface (Au | support/gap | Pd) with segment-specific:
   - differential capacitance C_i
   - potential of zero charge E_pzc,i
2) Computes reaction-plane potentials (segment averages at y = delta) as an affine function of the
   metal/mixed potential.
3) Couples those reaction-plane potentials to Frumkin-corrected Butler–Volmer kinetics for two
   half-reactions (one assigned to the Au segment, one to the Pd segment) and solves for the mixed potential.

Notes / Limitations
-------------------
- Electrostatics uses the Debye–Hückel approximation (linearized PB). This is controlled but strictly valid
  for |u| = |F*phi/(RT)| << 1. Use with caution at large interfacial potentials; treat trends as qualitative.
- The kinetic model is a single-step outer-sphere ET with Boltzmann partitioning at the reaction plane.
  You can replace bv_current_density() with your mechanism-specific expressions.

Dependencies: numpy, scipy (brentq), matplotlib (optional), pandas (optional)

Author: (generated by ChatGPT for your manuscript workflow)
"""

from dataclasses import dataclass
import math
import numpy as np
from scipy.optimize import brentq

# -----------------------------
# Physical constants
# -----------------------------
F = 96485.33212
R = 8.314462618
T = 298.15
eps0 = 8.8541878128e-12
eps_r_water = 78.5  # water ~25C

def debye_length(c_molar: float, z: int = 1, eps_r: float = eps_r_water, T_: float = T) -> float:
    """
    Debye length (m) for symmetric z:z electrolyte at concentration c_molar (mol/L).
    lambda_D = sqrt(eps*eps0*R*T / (2*z^2*F^2*c)), c in mol/m^3.
    """
    if c_molar <= 0:
        raise ValueError("c_molar must be > 0")
    c = c_molar * 1000.0  # mol/m^3
    return math.sqrt(eps_r * eps0 * R * T_ / (2 * (z**2) * (F**2) * c))


class EDL3SegmentDH:
    """
    Debye–Hückel solver for a 3-segment electrode in semi-infinite electrolyte.

    Dimensionless variables:
        u = (F/RT) * (phi - phi_bulk)
        x, y scaled by lambda_D
    Governing:
        (∂²/∂x² + ∂²/∂y²) u = u,     y>0
        u -> 0 as y -> ∞
    Boundary at y=0 on segment i:
        -∂u/∂y = C_i * (U_M - U_pzc,i - u(x,0))

    Expansion:
        u(x,0) = Σ a_n cos(k_n x), k_n = nπ/L_total
        u(x,y) = Σ a_n cos(k_n x) exp(-λ_n y), λ_n = sqrt(1+k_n^2)
    """

    def __init__(self, L_Au: float, L_gap: float, L_Pd: float, y_rp: float, N: int = 80):
        self.L_Au = float(L_Au)
        self.L_gap = float(L_gap)
        self.L_Pd = float(L_Pd)
        self.L_total = self.L_Au + self.L_gap + self.L_Pd
        self.segments = [
            (0.0, self.L_Au),
            (self.L_Au, self.L_Au + self.L_gap),
            (self.L_Au + self.L_gap, self.L_total),
        ]
        self.y_rp = float(y_rp)
        self.N = int(N)

        n = np.arange(self.N)
        self.k = n * np.pi / self.L_total
        self.lam = np.sqrt(1.0 + self.k**2)
        self.S = np.where(n == 0, self.L_total, self.L_total / 2.0)

        # Geometry-only integrals
        self.J_seg = []  # ∫ cos(k_n x) dx over each segment
        self.I_seg = []  # ∫ cos(k_n x) cos(k_m x) dx over each segment
        self.W_seg = []  # segment-average weights at y=y_rp

        for (xa, xb) in self.segments:
            J = self._int_cos_vec(xa, xb)
            I = self._int_coscos_mat(xa, xb)
            self.J_seg.append(J)
            self.I_seg.append(I)

            Lseg = xb - xa
            W = (J / Lseg) * np.exp(-self.lam * self.y_rp)
            self.W_seg.append(W)

    def _int_cos_vec(self, xa: float, xb: float) -> np.ndarray:
        N = self.N
        k = self.k
        J = np.empty(N)
        J[0] = xb - xa
        if N > 1:
            kn = k[1:]
            J[1:] = (np.sin(kn * xb) - np.sin(kn * xa)) / kn
        return J

    def _int_coscos_mat(self, xa: float, xb: float) -> np.ndarray:
        N = self.N
        k = self.k
        I = np.zeros((N, N))
        I[0, 0] = xb - xa

        if N > 1:
            intm = (np.sin(k[1:] * xb) - np.sin(k[1:] * xa)) / k[1:]
            I[0, 1:] = intm
            I[1:, 0] = intm

            knp = k[1:]
            kn = knp[:, None]
            km = knp[None, :]

            k_minus = kn - km
            k_plus = kn + km

            with np.errstate(divide="ignore", invalid="ignore"):
                I_sub = (np.sin(k_minus * xb) - np.sin(k_minus * xa)) / (2.0 * k_minus) + \
                        (np.sin(k_plus * xb) - np.sin(k_plus * xa)) / (2.0 * k_plus)

            # Diagonal fix (n=m): ∫ cos^2
            diag = 0.5 * (xb - xa) + (np.sin(2.0 * knp * xb) - np.sin(2.0 * knp * xa)) / (4.0 * knp)
            idx = np.arange(N - 1)
            I_sub[idx, idx] = diag

            I[1:, 1:] = I_sub

        return I

    def solve_affine_segment_averages(self, C_dim: np.ndarray, U_pzc: np.ndarray):
        """
        Compute affine mapping ū_i(U_M) = m_i U_M + b_i for each segment i.
        Returns list [(m_Au,b_Au),(m_gap,b_gap),(m_Pd,b_Pd)].
        """
        C_dim = np.asarray(C_dim, dtype=float)
        U_pzc = np.asarray(U_pzc, dtype=float)
        if C_dim.shape != (3,) or U_pzc.shape != (3,):
            raise ValueError("C_dim and U_pzc must be length-3 arrays")

        A = np.diag(self.lam * self.S)
        gU = np.zeros(self.N)
        g0 = np.zeros(self.N)

        for i in range(3):
            A = A + C_dim[i] * self.I_seg[i]
            gU = gU + C_dim[i] * self.J_seg[i]
            g0 = g0 - C_dim[i] * U_pzc[i] * self.J_seg[i]

        aU = np.linalg.solve(A, gU)
        a0 = np.linalg.solve(A, g0)

        seg_affine = []
        for i in range(3):
            m_i = float(np.dot(self.W_seg[i], aU))
            b_i = float(np.dot(self.W_seg[i], a0))
            seg_affine.append((m_i, b_i))

        return seg_affine


@dataclass
class HalfReaction:
    """
    Single-step outer-sphere ET:  O + n e <-> R
    """
    E_eq: float   # equilibrium potential (V, vs same reference as E_mix)
    i0: float     # exchange current density (A/m^2) in the "true/bulk" sense
    alpha: float = 0.5
    n: int = 1
    z_O: int = 1  # charge number of oxidized species O. Reduced has z_R=z_O-n.


def bv_current_density(rxn: HalfReaction, U: float, u_rp: float) -> float:
    """
    Frumkin-type BV current density with Boltzmann partitioning at reaction plane:

      j = i0 [ exp(-z_R u_rp) exp((1-α)nη) - exp(-z_O u_rp) exp(-α nη) ]

    where:
      U = (F/RT) E,  U_eq = (F/RT) E_eq,  η = U - U_eq
      u_rp = (F/RT) (phi_rp - phi_bulk)
      z_R = z_O - n
    """
    zO = rxn.z_O
    n = rxn.n
    zR = zO - n
    a = rxn.alpha
    Ueq = (F / (R * T)) * rxn.E_eq
    eta = U - Ueq
    return rxn.i0 * (math.exp(-zR * u_rp) * math.exp((1 - a) * n * eta) -
                     math.exp(-zO * u_rp) * math.exp(-a * n * eta))


def mixed_potential_3seg(
    c_M: float,
    L_Au_nm: float,
    L_gap_nm: float,
    L_Pd_nm: float,
    delta_nm: float,
    C_uFcm2: list,
    E_pzc: list,
    rxn_Au: HalfReaction,
    rxn_Pd: HalfReaction,
    N_modes: int = 60,
    E_bounds=(-0.5, 1.5),
):
    """
    Compute mixed potential E_mix (V) for a 3-segment electrode with two half-reactions:
        I_total(E) = j_Au(E)*A_Au + j_Pd(E)*A_Pd = 0

    Inputs:
      - c_M: electrolyte concentration (M)
      - L_*_nm: segment lengths in nm (Au | gap/support | Pd)
      - delta_nm: reaction plane distance above surface (nm)
      - C_uFcm2: [C_Au, C_gap, C_Pd] in µF/cm^2
      - E_pzc: [E_pzc_Au, E_pzc_gap, E_pzc_Pd] in V
      - rxn_Au, rxn_Pd: HalfReaction objects
      - N_modes: cosine modes in the spectral solution
      - E_bounds: bracket for root finding

    Returns:
      dict with E_mix, lambda_D, and reaction-plane potentials on Au and Pd segments.
    """
    lamD = debye_length(c_M, eps_r=eps_r_water, T_=T)  # m
    f = F / (R * T)

    # dimensionless geometry
    L_Au = (L_Au_nm * 1e-9) / lamD
    L_gap = (L_gap_nm * 1e-9) / lamD
    L_Pd = (L_Pd_nm * 1e-9) / lamD
    y_rp = (delta_nm * 1e-9) / lamD

    # dimensionless capacitance ratios: C_dim = C_phys/(ε κ) = C_phys*lambda_D/ε
    C_phys = np.array(C_uFcm2, dtype=float) * 0.01  # µF/cm^2 -> F/m^2
    C_dim = C_phys * lamD / (eps_r_water * eps0)

    U_pzc = np.array(E_pzc, dtype=float) * f

    edl = EDL3SegmentDH(L_Au, L_gap, L_Pd, y_rp, N=N_modes)
    seg_aff = edl.solve_affine_segment_averages(C_dim=C_dim, U_pzc=U_pzc)
    (m_Au, b_Au) = seg_aff[0]
    (m_Pd, b_Pd) = seg_aff[2]

    # segment areas per unit depth (m^2 per m depth)
    A_Au = L_Au_nm * 1e-9
    A_Pd = L_Pd_nm * 1e-9

    def I_total(E):
        U = f * E
        u_Au = m_Au * U + b_Au
        u_Pd = m_Pd * U + b_Pd
        jA = bv_current_density(rxn_Au, U, u_Au)
        jP = bv_current_density(rxn_Pd, U, u_Pd)
        return jA * A_Au + jP * A_Pd

    E_lo, E_hi = E_bounds
    # ensure bracket exists; scan if needed
    if I_total(E_lo) * I_total(E_hi) > 0:
        Es = np.linspace(E_lo, E_hi, 401)
        Is = np.array([I_total(Ee) for Ee in Es])
        idx = np.where(Is[:-1] * Is[1:] < 0)[0]
        if len(idx) == 0:
            raise RuntimeError("Root not bracketed; widen E_bounds or adjust kinetics.")
        E_lo, E_hi = Es[idx[0]], Es[idx[0] + 1]

    E_mix = brentq(I_total, E_lo, E_hi, xtol=1e-12, maxiter=200)
    U_mix = f * E_mix
    u_rp_Au = m_Au * U_mix + b_Au
    u_rp_Pd = m_Pd * U_mix + b_Pd

    return dict(
        E_mix=E_mix,
        lambdaD_nm=lamD * 1e9,
        u_rp_Au=u_rp_Au,
        u_rp_Pd=u_rp_Pd,
        phi_rp_Au_mV=u_rp_Au * (R*T/F) * 1e3,
        phi_rp_Pd_mV=u_rp_Pd * (R*T/F) * 1e3,
    )


if __name__ == "__main__":
    # Example run
    rxn_Au = HalfReaction(E_eq=0.0, i0=1e3, alpha=0.5, n=1, z_O=1)
    rxn_Pd = HalfReaction(E_eq=0.8, i0=1e3, alpha=0.5, n=1, z_O=1)

    out = mixed_potential_3seg(
        c_M=1e-2,
        L_Au_nm=5.0, L_gap_nm=2.0, L_Pd_nm=5.0,
        delta_nm=0.3,
        C_uFcm2=[20.0, 10.0, 20.0],
        E_pzc=[+0.2, 0.0, -0.2],
        rxn_Au=rxn_Au, rxn_Pd=rxn_Pd,
        N_modes=60,
        E_bounds=(-0.5, 1.5),
    )
    print(out)
